# This code was generated by a tool.
# @basketry/sorbet-validators@{{version}}
#
# Changes to this file may cause incorrect behavior and will be lost if
# the code is regenerated.

# typed: strict

module BasketryExample::V1::Types
  class ValidationError < T::Struct
    const :code, T.nilable(String)
    const :title, T.nilable(String)
    const :path, T.nilable(String)
  end
end
