# This code was generated by @basketry/sorbet-validators@{{version}}
#
# Changes to this file may cause incorrect behavior and will be lost if
# the code is regenerated.
#
# To make changes to the contents of this file:
# 1. Edit source/path.ext
# 2. Run the Basketry CLI
#
# About Basketry: https://github.com/basketry/basketry/wiki
# About @basketry/sorbet-validators: https://github.com/basketry/sorbet-validators#readme

# typed: strict

module BasketryExample::V1::Types
  class ValidationError < T::Struct
    const :code, T.nilable(String)
    const :title, T.nilable(String)
    const :path, T.nilable(String)
  end
end
